### ISSUE TITLE
download from website disappeared

### ISSUE THREAD

**Issue by jakobkroeker** [dstehle/fplll#33]
the download from webpage disappeared,
e.g. it is not possible to get 
http://perso.ens-lyon.fr/damien.stehle/fplll//libfplll-4.0.4.tar.gz

In our CAS we depend on specific versions and it also autodownloads the package.
Also I could not find any version tags on github yet.

We (Macaulay2) will manage to fix the problem on our side, but I strongly discourage to change the download 'interface' once it is established.

**Comment by dstehle** [comment]
Dear Jakob,

Thank you for using fplll.

I've put it back online. Note however that it is a deprecated version,
and the current version is the one available on github.

Best regards,
Damien

**Comment by pfasante** [comment]
Hi Jakob, Damien,

if you manage your source code via git, it could be a nice possibility
to add the github repo as a submodule to your repository. For example as
described here:
> https://git-scm.herokuapp.com/book/de/v1/Git-Tools-Submodule

I've recently used it for another project, and it looks quite nice for
dependencies like this (if installing the library is not enough or
similar things).

Regards,
Friedrich

**Comment by malb** [comment]
Closing this issue as it seems resolved.
